create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'room_status') then
    create type public.room_status as enum ('waiting', 'playing', 'finished');
  end if;

  if not exists (select 1 from pg_type where typname = 'stone_color') then
    create type public.stone_color as enum ('black', 'white');
  end if;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null check (char_length(nickname) between 1 and 24),
  rating integer not null default 0 check (rating >= 0),
  wins integer not null default 0 check (wins >= 0),
  losses integer not null default 0 check (losses >= 0),
  draws integer not null default 0 check (draws >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[A-Z0-9]{6}$'),
  status public.room_status not null default 'waiting',
  black_player uuid not null references public.profiles(id) on delete cascade,
  white_player uuid references public.profiles(id) on delete cascade,
  current_turn public.stone_color not null default 'black',
  winner public.stone_color,
  winning_player uuid references public.profiles(id) on delete set null,
  game_index integer not null default 1 check (game_index > 0),
  restart_black boolean not null default false,
  restart_white boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  finished_at timestamptz,
  constraint different_players check (white_player is null or black_player <> white_player)
);

create table if not exists public.moves (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  game_index integer not null check (game_index > 0),
  player_id uuid not null references public.profiles(id) on delete cascade,
  color public.stone_color not null,
  row integer not null check (row between 0 and 14),
  col integer not null check (col between 0 and 14),
  move_number integer not null check (move_number between 1 and 225),
  created_at timestamptz not null default now(),
  unique (room_id, game_index, row, col),
  unique (room_id, game_index, move_number)
);

create table if not exists public.game_results (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  game_index integer not null check (game_index > 0),
  black_player uuid not null references public.profiles(id) on delete cascade,
  white_player uuid not null references public.profiles(id) on delete cascade,
  winner_player uuid references public.profiles(id) on delete set null,
  outcome text not null check (outcome in ('black_win', 'white_win', 'draw')),
  created_at timestamptz not null default now(),
  unique (room_id, game_index)
);

create index if not exists moves_room_game_index_idx on public.moves (room_id, game_index, move_number);
create index if not exists rooms_code_idx on public.rooms (code);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists rooms_touch_updated_at on public.rooms;
create trigger rooms_touch_updated_at
before update on public.rooms
for each row execute function public.touch_updated_at();

create or replace function public.ensure_profile(p_nickname text)
returns public.profiles
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
  v_user uuid := auth.uid();
  v_nickname text := left(coalesce(nullif(trim(p_nickname), ''), 'Guest'), 24);
begin
  if v_user is null then
    raise exception 'Authentication is required.';
  end if;

  insert into public.profiles (id, nickname)
  values (v_user, v_nickname)
  on conflict (id) do update
    set nickname = excluded.nickname
  returning * into v_profile;

  return v_profile;
end;
$$;

create or replace function public.generate_room_code()
returns text
language sql
volatile
as $$
  select string_agg(substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', floor(random() * 32 + 1)::integer, 1), '')
  from generate_series(1, 6);
$$;

create or replace function public.create_room(p_nickname text)
returns public.rooms
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
  v_room public.rooms;
  v_code text;
  v_attempts integer := 0;
begin
  v_profile := public.ensure_profile(p_nickname);

  loop
    v_attempts := v_attempts + 1;
    v_code := public.generate_room_code();

    begin
      insert into public.rooms (code, black_player)
      values (v_code, v_profile.id)
      returning * into v_room;

      return v_room;
    exception
      when unique_violation then
        if v_attempts >= 20 then
          raise exception 'Could not generate a unique room code.';
        end if;
    end;
  end loop;
end;
$$;

create or replace function public.join_room(p_code text, p_nickname text)
returns public.rooms
language plpgsql
security definer
set search_path = public
as $$
declare
  v_profile public.profiles;
  v_room public.rooms;
  v_code text := upper(trim(p_code));
begin
  v_profile := public.ensure_profile(p_nickname);

  select *
  into v_room
  from public.rooms
  where code = v_code
  for update;

  if not found then
    raise exception 'Room not found.';
  end if;

  if v_room.black_player = v_profile.id or v_room.white_player = v_profile.id then
    return v_room;
  end if;

  if v_room.white_player is not null then
    raise exception 'Room is full.';
  end if;

  if v_room.status <> 'waiting' then
    raise exception 'Room is not joinable.';
  end if;

  update public.rooms
  set white_player = v_profile.id,
      status = 'playing',
      restart_black = false,
      restart_white = false
  where id = v_room.id
  returning * into v_room;

  return v_room;
end;
$$;

create or replace function public.count_stones_in_direction(
  p_room_id uuid,
  p_game_index integer,
  p_color public.stone_color,
  p_row integer,
  p_col integer,
  p_row_direction integer,
  p_col_direction integer
)
returns integer
language plpgsql
stable
set search_path = public
as $$
declare
  v_count integer := 0;
  v_row integer := p_row + p_row_direction;
  v_col integer := p_col + p_col_direction;
begin
  while v_row between 0 and 14 and v_col between 0 and 14 loop
    if exists (
      select 1
      from public.moves
      where room_id = p_room_id
        and game_index = p_game_index
        and color = p_color
        and row = v_row
        and col = v_col
    ) then
      v_count := v_count + 1;
      v_row := v_row + p_row_direction;
      v_col := v_col + p_col_direction;
    else
      exit;
    end if;
  end loop;

  return v_count;
end;
$$;

create or replace function public.has_five_or_more(
  p_room_id uuid,
  p_game_index integer,
  p_color public.stone_color,
  p_row integer,
  p_col integer
)
returns boolean
language plpgsql
stable
set search_path = public
as $$
begin
  if 1 + public.count_stones_in_direction(p_room_id, p_game_index, p_color, p_row, p_col, 0, 1)
       + public.count_stones_in_direction(p_room_id, p_game_index, p_color, p_row, p_col, 0, -1) >= 5 then
    return true;
  end if;

  if 1 + public.count_stones_in_direction(p_room_id, p_game_index, p_color, p_row, p_col, 1, 0)
       + public.count_stones_in_direction(p_room_id, p_game_index, p_color, p_row, p_col, -1, 0) >= 5 then
    return true;
  end if;

  if 1 + public.count_stones_in_direction(p_room_id, p_game_index, p_color, p_row, p_col, 1, 1)
       + public.count_stones_in_direction(p_room_id, p_game_index, p_color, p_row, p_col, -1, -1) >= 5 then
    return true;
  end if;

  if 1 + public.count_stones_in_direction(p_room_id, p_game_index, p_color, p_row, p_col, 1, -1)
       + public.count_stones_in_direction(p_room_id, p_game_index, p_color, p_row, p_col, -1, 1) >= 5 then
    return true;
  end if;

  return false;
end;
$$;

create or replace function public.submit_move(p_code text, p_row integer, p_col integer)
returns public.rooms
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_room public.rooms;
  v_color public.stone_color;
  v_next_turn public.stone_color;
  v_move_number integer;
  v_opponent uuid;
begin
  if v_user is null then
    raise exception 'Authentication is required.';
  end if;

  if p_row not between 0 and 14 or p_col not between 0 and 14 then
    raise exception 'Move is outside the board.';
  end if;

  select *
  into v_room
  from public.rooms
  where code = upper(trim(p_code))
  for update;

  if not found then
    raise exception 'Room not found.';
  end if;

  if v_room.status <> 'playing' then
    raise exception 'Game is not active.';
  end if;

  if v_room.black_player = v_user then
    v_color := 'black';
    v_next_turn := 'white';
    v_opponent := v_room.white_player;
  elsif v_room.white_player = v_user then
    v_color := 'white';
    v_next_turn := 'black';
    v_opponent := v_room.black_player;
  else
    raise exception 'Only room players can move.';
  end if;

  if v_room.white_player is null then
    raise exception 'Waiting for another player.';
  end if;

  if v_room.current_turn <> v_color then
    raise exception 'It is not your turn.';
  end if;

  if exists (
    select 1
    from public.moves
    where room_id = v_room.id
      and game_index = v_room.game_index
      and row = p_row
      and col = p_col
  ) then
    raise exception 'Cell is already occupied.';
  end if;

  select coalesce(max(move_number), 0) + 1
  into v_move_number
  from public.moves
  where room_id = v_room.id
    and game_index = v_room.game_index;

  insert into public.moves (room_id, game_index, player_id, color, row, col, move_number)
  values (v_room.id, v_room.game_index, v_user, v_color, p_row, p_col, v_move_number);

  if public.has_five_or_more(v_room.id, v_room.game_index, v_color, p_row, p_col) then
    update public.rooms
    set status = 'finished',
        winner = v_color,
        winning_player = v_user,
        finished_at = now(),
        restart_black = false,
        restart_white = false
    where id = v_room.id
    returning * into v_room;

    insert into public.game_results (room_id, game_index, black_player, white_player, winner_player, outcome)
    values (
      v_room.id,
      v_room.game_index,
      v_room.black_player,
      v_room.white_player,
      v_user,
      case when v_color = 'black' then 'black_win' else 'white_win' end
    )
    on conflict (room_id, game_index) do nothing;

    update public.profiles
    set rating = rating + 3,
        wins = wins + 1
    where id = v_user;

    update public.profiles
    set losses = losses + 1
    where id = v_opponent;

    return v_room;
  end if;

  if v_move_number >= 225 then
    update public.rooms
    set status = 'finished',
        winner = null,
        winning_player = null,
        finished_at = now(),
        restart_black = false,
        restart_white = false
    where id = v_room.id
    returning * into v_room;

    insert into public.game_results (room_id, game_index, black_player, white_player, winner_player, outcome)
    values (v_room.id, v_room.game_index, v_room.black_player, v_room.white_player, null, 'draw')
    on conflict (room_id, game_index) do nothing;

    update public.profiles
    set rating = rating + 1,
        draws = draws + 1
    where id in (v_room.black_player, v_room.white_player);

    return v_room;
  end if;

  update public.rooms
  set current_turn = v_next_turn
  where id = v_room.id
  returning * into v_room;

  return v_room;
end;
$$;

create or replace function public.request_restart(p_code text)
returns public.rooms
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_room public.rooms;
  v_next_black uuid;
  v_next_white uuid;
begin
  if v_user is null then
    raise exception 'Authentication is required.';
  end if;

  select *
  into v_room
  from public.rooms
  where code = upper(trim(p_code))
  for update;

  if not found then
    raise exception 'Room not found.';
  end if;

  if v_room.status <> 'finished' then
    raise exception 'Game is not finished.';
  end if;

  if v_user = v_room.black_player then
    update public.rooms
    set restart_black = true
    where id = v_room.id
    returning * into v_room;
  elsif v_user = v_room.white_player then
    update public.rooms
    set restart_white = true
    where id = v_room.id
    returning * into v_room;
  else
    raise exception 'Only room players can request restart.';
  end if;

  if v_room.restart_black and v_room.restart_white then
    v_next_black := v_room.white_player;
    v_next_white := v_room.black_player;

    update public.rooms
    set status = 'playing',
        black_player = v_next_black,
        white_player = v_next_white,
        current_turn = 'black',
        winner = null,
        winning_player = null,
        game_index = game_index + 1,
        restart_black = false,
        restart_white = false,
        finished_at = null
    where id = v_room.id
    returning * into v_room;
  end if;

  return v_room;
end;
$$;

alter table public.profiles enable row level security;
alter table public.rooms enable row level security;
alter table public.moves enable row level security;
alter table public.game_results enable row level security;

drop policy if exists "profiles are readable by authenticated users" on public.profiles;
create policy "profiles are readable by authenticated users"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "users can update their own profile" on public.profiles;
create policy "users can update their own profile"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "room players can read their rooms" on public.rooms;
create policy "room players can read their rooms"
on public.rooms for select
to authenticated
using (black_player = auth.uid() or white_player = auth.uid());

drop policy if exists "room players can read moves" on public.moves;
create policy "room players can read moves"
on public.moves for select
to authenticated
using (
  exists (
    select 1
    from public.rooms
    where rooms.id = moves.room_id
      and (rooms.black_player = auth.uid() or rooms.white_player = auth.uid())
  )
);

drop policy if exists "room players can read results" on public.game_results;
create policy "room players can read results"
on public.game_results for select
to authenticated
using (black_player = auth.uid() or white_player = auth.uid());

grant usage on schema public to authenticated;
grant select on public.profiles, public.rooms, public.moves, public.game_results to authenticated;
grant execute on function public.create_room(text) to authenticated;
grant execute on function public.join_room(text, text) to authenticated;
grant execute on function public.submit_move(text, integer, integer) to authenticated;
grant execute on function public.request_restart(text) to authenticated;

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    begin
      alter publication supabase_realtime add table public.rooms;
    exception when duplicate_object then
      null;
    end;

    begin
      alter publication supabase_realtime add table public.moves;
    exception when duplicate_object then
      null;
    end;

    begin
      alter publication supabase_realtime add table public.profiles;
    exception when duplicate_object then
      null;
    end;
  end if;
end $$;
